### ISSUE TITLE
Opens and immediately closes

### ISSUE THREAD

**Issue by tristan-mcinnis** [locaal-ai/note-taker#6]
Hey! I'm super excited about the possibility for this note Taking app. I've tried both the cpu version and the CUDA version on Windows 11 and it seems like after the installation, when I try to open them, they open briefly and then they close very quickly.

I'll do a little bit more to see maybe some restarts, maybe some reinstallation to see if there are any issues. but just wanted to raise this here first in case it was something that others are also having.

**Comment by royshil** [comment]
Sorry about that!
One thing to try is to run it from e.g. PowerShell and watch for any errors that pop off
for example
![image](https://github.com/user-attachments/assets/0da7e4b7-e20b-46e6-b805-4cafcd28e284)

**Comment by tristan-mcinnis** [comment]
> (base) PS C:\Users\trist> & "C:\Program Files\LocaalNoteTaker\note-taker.exe"
Traceback (most recent call last):
  File "app.py", line 18, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 378, in exec_module
  File "notes_editor_components.py", line 14, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 378, in exec_module
  File "textual_transcription_textarea.py", line 12, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 378, in exec_module
  File "Transcriber.py", line 2, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 378, in exec_module
  File "simpler_whisper\__init__.py", line 1, in <module>
ImportError: DLL load failed while importing _whisper_cpp: The specified procedure could not be found.
[PYI-29920:ERROR] Failed to execute script 'app' due to unhandled exception!
(base) PS C:\Users\trist>

> 
Think this has to do with simple-whisper. I couldn't pip install that eitehr at the moment :)

**Comment by royshil** [comment]
@tristan-mcinnis are you using the CPU or CUDA version?
it's missing DLLs... so maybe they are not placed in the right place, which i canfix

**Comment by tristan-mcinnis** [comment]
I've tried both with the same result.

**Comment by DannieBGoode** [comment]
I get the same error, the half a second that the cmd is open I  see this error
![localNoteTaker](https://github.com/user-attachments/assets/7aaa8cfe-18d9-4ac8-a91c-b3133a7fb455)

I am using Windows 10 with:
- git version 2.38.1.windows.1
- Python 3.11.8

I installed it through the installer found in the releases page for `note-taker-windows-cuda-0.0.2` and I am using a GeForce GTX 1070.

For the installer version are there any dependencies that must be installed prior to NoteTaker?

**Comment by JdotCarver** [comment]
Unless I'm confused. This is supposed behavior.
As per the usage instructions in the [Readme.md](https://github.com/locaal-ai/note-taker?tab=readme-ov-file#usage), you never launch the exe.
