### ISSUE TITLE
Error on launch "access violation reading 0x0000000000000078"

### ISSUE THREAD

**Issue by JdotCarver** [locaal-ai/note-taker#8]
Tried all afternoon to get this working.

- Running Python 3.11.9
- All dependencies installed
- Both CUDA and CPU versions tested
- Even got the simpler_whisper-0.2.2+cpu-cp311-cp311-win_amd64.whl from #3 

Stuck here. When I launch the main.py I get this. Any ideas ?

```C:\Program Files\LocaalNoteTaker\note-taker\src>py main.py
Starting Note Taker
Traceback (most recent call last):
  File "C:\Program Files\LocaalNoteTaker\note-taker\src\main.py", line 15, in <module>
    LanguageModel()  # Warm up the LLM
    ^^^^^^^^^^^^^^^
  File "C:\Program Files\LocaalNoteTaker\note-taker\src\llm\model.py", line 31, in __init__
    self.set_model(None)
  File "C:\Program Files\LocaalNoteTaker\note-taker\src\llm\model.py", line 39, in set_model
    self.llm = Llama.from_pretrained(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JdotCarver\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_cpp\llama.py", line 2353, in from_pretrained
    return cls(
           ^^^^
  File "C:\Users\JdotCarver\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_cpp\llama.py", line 369, in __init__
    internals.LlamaModel(
  File "C:\Users\JdotCarver\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_cpp\_internals.py", line 51, in __init__
    model = llama_cpp.llama_load_model_from_file(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: exception: access violation reading 0x0000000000000078

**Comment by gith-hubtest** [comment]
i was **not** able to solve the issue directly, **but** indirectly it worked after i replaced the `llama_cpp` in the `site-packages`
* install note-taker for windows with  the installer: : `note-taker-windows-cpu-0.0.2 `
* replace `llama_cpp` and `llama_cpp_python-0.3.1.dist-info` from the windows .exe installation `_internals` folder into `site-packages`

app launches now, but struggling with listening to mic... which ~~could be~~ was my device issue itself and the app does not break down with this issue anymore.

```
  File "E:\localnotes_ai\note-taker\src\audio\AudioCapture.py", line 100, in stop_recording
    if self.mic_stream:
       ^^^^^^^^^^^^^^^
AttributeError: 'AudioCapture' object has no attribute 'mic_stream'
```

**Comment by JdotCarver** [comment]
Thanks for the update. 🙏
